# Generated by Django 4.0.3 on 2022-07-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0016_examen_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='hash',
        ),
    ]
