# Generated by Django 4.0.3 on 2022-07-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0017_remove_transcript_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='statement_footprint',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
