# Generated by Django 4.0.3 on 2022-07-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0019_alter_evaluation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
